### ISSUE TITLE
Visualiser fails to start on Arch linux

### ISSUE THREAD

**Issue by ReticulatedIbex** [Auburn/FastNoiseLite#75]
Hi, 

The linux build of FastNoiseLiteGUI fails to start on Arch Linux with the following error

`Exception in Gtk# callback delegate
  Note: Applications can use GLib.ExceptionManager.UnhandledException to handle the exception.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Gtk.SpinButton.OutputSignalCallback(IntPtr inst, IntPtr gch)
   at GLib.ExceptionManager.RaiseUnhandledException(Exception e, Boolean is_terminal)
   at Gtk.SpinButton.OutputSignalCallback(IntPtr inst, IntPtr gch)
   at Gtk.SpinButton.set_Value(Double value)
   at Eto.GtkSharp.Forms.Controls.NumericStepperHandler.set_Value(Double value)
   at FastNoiseLiteGUI..ctor()
   at Program.Main(String[] args)`

A quick look at Eto release notes brings up this https://github.com/picoe/Eto/issues/1914 which looks to be the problem here, so I  grabbed the source code and bumped Eto to 2.5.11 and it did indeed fix it.

**Comment by Auburn** [comment]
Thanks, I'll look into it

**Comment by Auburn** [comment]
Should be fixed in latest [release] (https://github.com/Auburn/FastNoiseLite/releases/tag/v1.0.3)
